name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Set current date as env variable
        id: tag_name_step
        shell: pwsh
        run: '[Environment]::Version.ToString() + "_" + [DateTime]::Now.ToString("yyyy-m-dTHH:MM:ss") >> $TAG_NAME'

      - name: Create release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ TAG_NAME }}
          prerelease: true
          title: Development Build

  build:
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64
          - os: windows-latest
            runtime: win-x64

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish --no-restore --nologo -c Release

      - name: Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archiving
        shell: pwsh
        run: Compress-Archive ConsoleApp1/bin/Release/net6.0/publish/* ConsoleApp1/bin/Release/net6.0/publish/${{ matrix.runtime }}.zip -r ${{ matrix.runtime }}

      - name: Upload asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ConsoleApp1/bin/Release/net6.0/publish/${{ matrix.runtime }}.zip
