name: ".NET"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.3.4"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1.8.0"
        with:
          dotnet-version: "6.0.x"

      - name: "Restore dependencies"
        run: "dotnet restore"

      - name: "Publish"
        run: "dotnet publish --no-restore --nolog -c Release"

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "ConsoleApp1\\bin\\Release\\net6.0\\publish"
