name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.tag_name_step.outputs.TAG_NAME }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Set current date as env variable
        id: tag_name_step
        shell: pwsh
        run: |
          $v = "v" + [Environment]::Version.ToString() + "-" + [DateTime]::Now.ToString("yyyymdHHMMss")
          echo "::set-output name=TAG_NAME::$v"

  build:
    runs-on: ubuntu-latest
    needs: [set_variables]

    steps:
      - uses: actions/checkout@v2.3.4

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v1.8.0
      #   with:
      #     dotnet-version: 6.0.x
      #     include-prerelease: true

      # - name: .NET
      #   run: dotnet --list-sdks

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish --no-restore --nologo -c Release

      - name: Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archiving
        shell: pwsh
        run: Compress-Archive ConsoleApp1/bin/Release/net6.0/publish/* ConsoleApp1/bin/Release/net6.0/publish/win-x64.zip

    deploy:
      runs-on: ubuntu-latest
      needs: [build]
        - name: Release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: ${{ needs.set_variables.outputs.TAG_NAME }}
            prerelease: true
            title: Development Build
            files: ConsoleApp1/bin/Release/net6.0/publish/win-x64.zip
