name: ".NET"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  set_variables:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set current date as env variable"
        run: '[Environment]::Version.ToString() + "_" + [DateTime]::Now.ToString("yyyy-m-dTHH:MM:ss")'

  build:
    runs-on: "ubuntu-latest"
    needs: ["set_variables"]

    steps:
      - uses: "actions/checkout@v2.3.4"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1.8.0"
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: "Restore dependencies"
        run: "dotnet restore"

      - name: "Publish"
        run: "dotnet publish --no-restore --nologo -c Release"

      - name: "Changelog"
        uses: "scottbrenner/generate-changelog-action@master"
        id: "Changelog"
        env:
          REPO: ${{ github.repository }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "ConsoleApp1\\bin\\Release\\net6.0\\publish\\**\\*"
